In [8]:
import pandas_ta as ta
import pandas as pd

## Fetching data

In [15]:
df = pd.DataFrame()
df = df.ta.ticker("aapl")

In [10]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1980-12-12 00:00:00-05:00,0.100039,0.100474,0.100039,0.100039,469033600,0.0,0.0
1980-12-15 00:00:00-05:00,0.095255,0.095255,0.094820,0.094820,175884800,0.0,0.0
1980-12-16 00:00:00-05:00,0.088296,0.088296,0.087861,0.087861,105728000,0.0,0.0
1980-12-17 00:00:00-05:00,0.090035,0.090470,0.090035,0.090035,86441600,0.0,0.0
1980-12-18 00:00:00-05:00,0.092646,0.093081,0.092646,0.092646,73449600,0.0,0.0
...,...,...,...,...,...,...,...
2022-10-03 00:00:00-04:00,138.210007,143.070007,137.690002,142.449997,114311700,0.0,0.0
2022-10-04 00:00:00-04:00,145.029999,146.220001,144.259995,146.100006,87830100,0.0,0.0
2022-10-05 00:00:00-04:00,144.070007,147.380005,143.009995,146.399994,79471000,0.0,0.0
2022-10-06 00:00:00-04:00,145.809998,147.539993,145.220001,145.429993,68402200,0.0,0.0
2022-10-07 00:00:00-04:00,142.539993,143.100006,139.449997,140.089996,85859100,0.0,0.0

In [16]:
# Valid periods: 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max

# Valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo

df = df.ta.ticker("aapl", period="1mo", interval="1h")

In [17]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
2022-09-08 09:30:00-04:00,154.639999,155.839996,154.369995,154.919998,20423405,0,0
2022-09-08 10:30:00-04:00,154.910004,156.360001,154.700195,155.990005,9445752,0,0
2022-09-08 11:30:00-04:00,155.985001,156.190002,152.679993,153.149902,12280244,0,0
2022-09-08 12:30:00-04:00,153.149994,154.020004,152.695007,153.733505,10943346,0,0
2022-09-08 13:30:00-04:00,153.740005,154.139999,153.229996,153.789993,7342717,0,0
...,...,...,...,...,...,...,...
2022-10-07 12:30:00-04:00,140.669998,140.720001,139.940002,140.279999,7685803,0,0
2022-10-07 13:30:00-04:00,140.145004,140.600006,140.035004,140.077896,6175166,0,0
2022-10-07 14:30:00-04:00,140.070007,140.535004,139.600006,139.721893,8536199,0,0
2022-10-07 15:30:00-04:00,139.720001,140.490005,139.445007,140.080002,13306374,0,0
2022-10-07 16:00:00-04:00,140.089996,140.089996,140.089996,140.089996,0,0,0

## Indicators

In [10]:
help(df.ta)

Help on AnalysisIndicators in module pandas_ta.core object:

class AnalysisIndicators(BasePandasObject)
 |  AnalysisIndicators(pandas_obj)
 |
 |  This Pandas Extension is named 'ta' for Technical Analysis. In other words,
 |  it is a Numerical Time Series Feature Generator where the Time Series data
 |  is biased towards Financial Market data; typical data includes columns
 |  named :"open", "high", "low", "close", "volume".
 |
 |  This TA Library hopefully allows you to apply familiar and unique Technical
 |  Analysis Indicators easily with the DataFrame Extension named 'ta'. Even
 |  though 'ta' is a Pandas DataFrame Extension, you can still call Technical
 |  Analysis indicators individually if you are more comfortable with that
 |  approach or it allows you to easily and automatically apply the indicators
 |  with the strategy method. See: help(ta.strategy).
 |
 |  By default, the 'ta' extension uses lower case column names: open, high,
 |  low, close, and volume. You can override the defaults by providing the it's
 |  replacement name when calling the indicator. For example, to call the
 |  indicator hl2().
 |
 |  With 'default' columns: open, high, low, close, and volume.
 |  >>> df.ta.hl2()
 |  >>> df.ta(kind="hl2")
 |
 |  With DataFrame columns: Open, High, Low, Close, and Volume.
 |  >>> df.ta.hl2(high="High", low="Low")
 |  >>> df.ta(kind="hl2", high="High", low="Low")
 |
 |  If you do not want to use a DataFrame Extension, just call it normally.
 |  >>> sma10 = ta.sma(df["Close"]) # Default length=10
 |  >>> sma50 = ta.sma(df["Close"], length=50)
 |  >>> ichimoku, span = ta.ichimoku(df["High"], df["Low"], df["Close"])
 |
 |  Args:
 |      kind (str, optional): Default: None. Kind is the 'name' of the indicator.
 |          It converts kind to lowercase before calling.
 |      timed (bool, optional): Default: False. Curious about the execution
 |          speed?
 |      kwargs: Extension specific modifiers.
 |          append (bool, optional): Default: False. When True, it appends the
 |          resultant column(s) to the DataFrame.
 |
 |  Returns:
 |      Most Indicators will return a Pandas Series. Others like MACD, BBANDS,
 |      KC, et al will return a Pandas DataFrame. Ichimoku on the other hand
 |      will return two DataFrames, the Ichimoku DataFrame for the known period
 |      and a Span DataFrame for the future of the Span values.
 |
 |  Let's get started!
 |
 |  1. Loading the 'ta' module:
 |  >>> import pandas as pd
 |  >>> import ta as ta
 |
 |  2. Load some data:
 |  >>> df = pd.read_csv("AAPL.csv", index_col="date", parse_dates=True)
 |
 |  3. Help!
 |  3a. General Help:
 |  >>> help(df.ta)
 |  >>> df.ta()
 |  3b. Indicator Help:
 |  >>> help(ta.apo)
 |  3c. Indicator Extension Help:
 |  >>> help(df.ta.apo)
 |
 |  4. Ways of calling an indicator.
 |  4a. Standard: Calling just the APO indicator without "ta" DataFrame extension.
 |  >>> ta.apo(df["close"])
 |  4b. DataFrame Extension: Calling just the APO indicator with "ta" DataFrame extension.
 |  >>> df.ta.apo()
 |  4c. DataFrame Extension (kind): Calling APO using 'kind'
 |  >>> df.ta(kind="apo")
 |  4d. Strategy:
 |  >>> df.ta.strategy("All") # Default
 |  >>> df.ta.strategy(ta.Strategy("My Strat", ta=[{"kind": "apo"}])) # Custom
 |
 |  5. Working with kwargs
 |  5a. Append the result to the working df.
 |  >>> df.ta.apo(append=True)
 |  5b. Timing an indicator.
 |  >>> apo = df.ta(kind="apo", timed=True)
 |  >>> print(apo.timed)
 |
 |  Method resolution order:
 |      AnalysisIndicators
 |      BasePandasObject
 |      pandas.core.base.PandasObject
 |      pandas.core.accessor.DirNamesMixin
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __call__(self, kind: str = None, timed: bool = False, version: bool = False, **kwargs)
 |      Call self as a function.
 |
 |  __init__(self, pandas_obj)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  aberration(self, length=None, atr_length=None, offset=None, **kwargs)
 |      # Volatility
 |
 |  above(self, asint=True, offset=None, **kwargs)
 |      # Utility
 |
 |  above_value(self, value=None, asint=True, offset=None, **kwargs)
 |
 |  accbands(self, length=None, c=None, mamode=None, offset=None, **kwargs)
 |
 |  ad(self, open_=None, signed=True, offset=None, **kwargs)
 |      # Volume
 |
 |  adosc(self, open_=None, fast=None, slow=None, signed=True, offset=None, **kwargs)
 |
 |  adx(self, length=None, lensig=None, mamode=None, scalar=None, drift=None, offset=None, **kwargs)
 |      # Trend
 |
 |  alma(self, length=None, sigma=None, distribution_offset=None, offset=None, **kwargs)
 |      # Overlap
 |
 |  amat(self, fast=None, slow=None, mamode=None, lookback=None, offset=None, **kwargs)
 |
 |  ao(self, fast=None, slow=None, offset=None, **kwargs)
 |      # Momentum
 |
 |  aobv(self, fast=None, slow=None, mamode=None, max_lookback=None, min_lookback=None, offset=None, **kwargs)
 |
 |  apo(self, fast=None, slow=None, mamode=None, offset=None, **kwargs)
 |
 |  aroon(self, length=None, scalar=None, offset=None, **kwargs)
 |
 |  atr(self, length=None, mamode=None, offset=None, **kwargs)
 |
 |  bbands(self, length=None, std=None, mamode=None, offset=None, **kwargs)
 |
 |  below(self, asint=True, offset=None, **kwargs)
 |
 |  below_value(self, value=None, asint=True, offset=None, **kwargs)
 |
 |  bias(self, length=None, mamode=None, offset=None, **kwargs)
 |
 |  bop(self, percentage=False, offset=None, **kwargs)
 |
 |  brar(self, length=None, scalar=None, drift=None, offset=None, **kwargs)
 |
 |  cci(self, length=None, c=None, offset=None, **kwargs)
 |
 |  cdl_pattern(self, name='all', offset=None, **kwargs)
 |      # Public DataFrame Methods: Indicators and Utilities
 |      # Candles
 |
 |  cdl_z(self, full=None, offset=None, **kwargs)
 |
 |  cfo(self, length=None, offset=None, **kwargs)
 |
 |  cg(self, length=None, offset=None, **kwargs)
 |
 |  chop(self, length=None, atr_length=None, scalar=None, drift=None, offset=None, **kwargs)
 |
 |  cksp(self, p=None, x=None, q=None, mamode=None, offset=None, **kwargs)
 |
 |  cmf(self, open_=None, length=None, offset=None, **kwargs)
 |
 |  cmo(self, length=None, scalar=None, drift=None, offset=None, **kwargs)
 |
 |  constants(self, append: bool, values: list)
 |      Constants
 |
 |      Add or remove constants to the DataFrame easily with Numpy's arrays or
 |      lists. Useful when you need easily accessible horizontal lines for
 |      charting.
 |
 |      Add constant '1' to the DataFrame
 |      >>> df.ta.constants(True, [1])
 |      Remove constant '1' to the DataFrame
 |      >>> df.ta.constants(False, [1])
 |
 |      Adding constants for charting
 |      >>> import numpy as np
 |      >>> chart_lines = np.append(np.arange(-4, 5, 1), np.arange(-100, 110, 10))
 |      >>> df.ta.constants(True, chart_lines)
 |      Removing some constants from the DataFrame
 |      >>> df.ta.constants(False, np.array([-60, -40, 40, 60]))
 |
 |      Args:
 |          append (bool): If True, appends a Numpy range of constants to the
 |              working DataFrame.  If False, it removes the constant range from
 |              the working DataFrame. Default: None.
 |
 |      Returns:
 |          Returns the appended constants
 |          Returns nothing to the user.  Either adds or removes constant ranges
 |          from the working DataFrame.
 |
 |  coppock(self, length=None, fast=None, slow=None, offset=None, **kwargs)
 |
 |  cross(self, above=True, asint=True, offset=None, **kwargs)
 |
 |  cross_value(self, value=None, above=True, asint=True, offset=None, **kwargs)
 |
 |  cti(self, length=None, offset=None, **kwargs)
 |
 |  decay(self, length=None, mode=None, offset=None, **kwargs)
 |
 |  decreasing(self, length=None, strict=None, asint=None, offset=None, **kwargs)
 |
 |  dema(self, length=None, offset=None, **kwargs)
 |
 |  dm(self, drift=None, offset=None, mamode=None, **kwargs)
 |
 |  donchian(self, lower_length=None, upper_length=None, offset=None, **kwargs)
 |
 |  dpo(self, length=None, centered=True, offset=None, **kwargs)
 |
 |  ebsw(self, close=None, length=None, bars=None, offset=None, **kwargs)
 |      # Cycles
 |
 |  efi(self, length=None, mamode=None, offset=None, drift=None, **kwargs)
 |
 |  ema(self, length=None, offset=None, **kwargs)
 |
 |  entropy(self, length=None, base=None, offset=None, **kwargs)
 |      # Statistics
 |
 |  eom(self, length=None, divisor=None, offset=None, drift=None, **kwargs)
 |
 |  er(self, length=None, drift=None, offset=None, **kwargs)
 |
 |  eri(self, length=None, offset=None, **kwargs)
 |
 |  fisher(self, length=None, signal=None, offset=None, **kwargs)
 |
 |  fwma(self, length=None, offset=None, **kwargs)
 |
 |  ha(self, offset=None, **kwargs)
 |
 |  hilo(self, high_length=None, low_length=None, mamode=None, offset=None, **kwargs)
 |
 |  hl2(self, offset=None, **kwargs)
 |
 |  hlc3(self, offset=None, **kwargs)
 |
 |  hma(self, length=None, offset=None, **kwargs)
 |
 |  hwc(self, na=None, nb=None, nc=None, nd=None, scalar=None, offset=None, **kwargs)
 |
 |  hwma(self, na=None, nb=None, nc=None, offset=None, **kwargs)
 |
 |  ichimoku(self, tenkan=None, kijun=None, senkou=None, include_chikou=True, offset=None, **kwargs)
 |
 |  increasing(self, length=None, strict=None, asint=None, offset=None, **kwargs)
 |
 |  indicators(self, **kwargs)
 |      List of Indicators
 |
 |      kwargs:
 |          as_list (bool, optional): When True, it returns a list of the
 |              indicators. Default: False.
 |          exclude (list, optional): The passed in list will be excluded
 |              from the indicators list. Default: None.
 |
 |      Returns:
 |          Prints the list of indicators. If as_list=True, then a list.
 |
 |  inertia(self, length=None, rvi_length=None, scalar=None, refined=None, thirds=None, mamode=None, drift=None, offset=None, **kwargs)
 |
 |  jma(self, length=None, phase=None, offset=None, **kwargs)
 |
 |  kama(self, length=None, fast=None, slow=None, offset=None, **kwargs)
 |
 |  kc(self, length=None, scalar=None, mamode=None, offset=None, **kwargs)
 |
 |  kdj(self, length=None, signal=None, offset=None, **kwargs)
 |
 |  kst(self, roc1=None, roc2=None, roc3=None, roc4=None, sma1=None, sma2=None, sma3=None, sma4=None, signal=None, offset=None, **kwargs)
 |
 |  kurtosis(self, length=None, offset=None, **kwargs)
 |
 |  kvo(self, fast=None, slow=None, length_sig=None, mamode=None, offset=None, drift=None, **kwargs)
 |
 |  linreg(self, length=None, offset=None, adjust=None, **kwargs)
 |
 |  log_return(self, length=None, cumulative=False, percent=False, offset=None, **kwargs)
 |      # Performance
 |
 |  long_run(self, fast=None, slow=None, length=None, offset=None, **kwargs)
 |
 |  macd(self, fast=None, slow=None, signal=None, offset=None, **kwargs)
 |
 |  mad(self, length=None, offset=None, **kwargs)
 |
 |  massi(self, fast=None, slow=None, offset=None, **kwargs)
 |
 |  mcgd(self, length=None, offset=None, **kwargs)
 |
 |  median(self, length=None, offset=None, **kwargs)
 |
 |  mfi(self, length=None, drift=None, offset=None, **kwargs)
 |
 |  midpoint(self, length=None, offset=None, **kwargs)
 |
 |  midprice(self, length=None, offset=None, **kwargs)
 |
 |  mom(self, length=None, offset=None, **kwargs)
 |
 |  natr(self, length=None, mamode=None, scalar=None, offset=None, **kwargs)
 |
 |  nvi(self, length=None, initial=None, signed=True, offset=None, **kwargs)
 |
 |  obv(self, offset=None, **kwargs)
 |
 |  ohlc4(self, offset=None, **kwargs)
 |
 |  pdist(self, drift=None, offset=None, **kwargs)
 |
 |  percent_return(self, length=None, cumulative=False, percent=False, offset=None, **kwargs)
 |
 |  pgo(self, length=None, offset=None, **kwargs)
 |
 |  ppo(self, fast=None, slow=None, scalar=None, mamode=None, offset=None, **kwargs)
 |
 |  psar(self, af0=None, af=None, max_af=None, offset=None, **kwargs)
 |
 |  psl(self, open_=None, length=None, scalar=None, drift=None, offset=None, **kwargs)
 |
 |  pvi(self, length=None, initial=None, signed=True, offset=None, **kwargs)
 |
 |  pvo(self, fast=None, slow=None, signal=None, scalar=None, offset=None, **kwargs)
 |
 |  pvol(self, volume=None, offset=None, **kwargs)
 |
 |  pvr(self, **kwargs)
 |
 |  pvt(self, offset=None, **kwargs)
 |
 |  pwma(self, length=None, offset=None, **kwargs)
 |
 |  qqe(self, length=None, smooth=None, factor=None, mamode=None, offset=None, **kwargs)
 |
 |  qstick(self, length=None, offset=None, **kwargs)
 |
 |  quantile(self, length=None, q=None, offset=None, **kwargs)
 |
 |  rma(self, length=None, offset=None, **kwargs)
 |
 |  roc(self, length=None, offset=None, **kwargs)
 |
 |  rsi(self, length=None, scalar=None, drift=None, offset=None, **kwargs)
 |
 |  rsx(self, length=None, drift=None, offset=None, **kwargs)
 |
 |  rvgi(self, length=None, swma_length=None, offset=None, **kwargs)
 |
 |  rvi(self, length=None, scalar=None, refined=None, thirds=None, mamode=None, drift=None, offset=None, **kwargs)
 |
 |  short_run(self, fast=None, slow=None, length=None, offset=None, **kwargs)
 |
 |  sinwma(self, length=None, offset=None, **kwargs)
 |
 |  skew(self, length=None, offset=None, **kwargs)
 |
 |  slope(self, length=None, offset=None, **kwargs)
 |
 |  sma(self, length=None, offset=None, **kwargs)
 |
 |  smi(self, fast=None, slow=None, signal=None, scalar=None, offset=None, **kwargs)
 |
 |  squeeze(self, bb_length=None, bb_std=None, kc_length=None, kc_scalar=None, mom_length=None, mom_smooth=None, use_tr=None, mamode=None, offset=None, **kwargs)
 |
 |  squeeze_pro(self, bb_length=None, bb_std=None, kc_length=None, kc_scalar_wide=None, kc_scalar_normal=None, kc_scalar_narrow=None, mom_length=None, mom_smooth=None, use_tr=None, mamode=None, offset=None, **kwargs)
 |
 |  ssf(self, length=None, poles=None, offset=None, **kwargs)
 |
 |  stc(self, ma1=None, ma2=None, osc=None, tclength=None, fast=None, slow=None, factor=None, offset=None, **kwargs)
 |
 |  stdev(self, length=None, offset=None, **kwargs)
 |
 |  stoch(self, fast_k=None, slow_k=None, slow_d=None, mamode=None, offset=None, **kwargs)
 |
 |  stochrsi(self, length=None, rsi_length=None, k=None, d=None, mamode=None, offset=None, **kwargs)
 |
 |  strategy(self, *args, **kwargs)
 |      Strategy Method
 |
 |      An experimental method that by default runs all applicable indicators.
 |      Future implementations will allow more specific indicator generation
 |      with possibly as json, yaml config file or an sqlite3 table.
 |
 |
 |      Kwargs:
 |          chunksize (bool): Adjust the chunksize for the Multiprocessing Pool.
 |              Default: Number of cores of the OS
 |          exclude (list): List of indicator names to exclude. Some are
 |              excluded by default for various reasons; they require additional
 |              sources, performance (td_seq), not a ohlcv chart (vp) etc.
 |          name (str): Select all indicators or indicators by
 |              Category such as: "candles", "cycles", "momentum", "overlap",
 |              "performance", "statistics", "trend", "volatility", "volume", or
 |              "all". Default: "all"
 |          ordered (bool): Whether to run "all" in order. Default: True
 |          timed (bool): Show the process time of the strategy().
 |              Default: False
 |          verbose (bool): Provide some additional insight on the progress of
 |              the strategy() execution. Default: False
 |
 |  supertrend(self, period=None, multiplier=None, mamode=None, drift=None, offset=None, **kwargs)
 |
 |  swma(self, length=None, offset=None, **kwargs)
 |
 |  t3(self, length=None, a=None, offset=None, **kwargs)
 |
 |  td_seq(self, asint=None, offset=None, show_all=None, **kwargs)
 |
 |  tema(self, length=None, offset=None, **kwargs)
 |
 |  thermo(self, long=None, short=None, length=None, mamode=None, drift=None, offset=None, **kwargs)
 |
 |  ticker(self, ticker: str, **kwargs)
 |      ticker
 |
 |      This method downloads Historical Data if the package yfinance is installed.
 |      Additionally it can run a ta.Strategy; Builtin or Custom. It returns a
 |      DataFrame if there the DataFrame is not empty, otherwise it exits. For
 |      additional yfinance arguments, use help(ta.yf).
 |
 |      Historical Data
 |      >>> df = df.ta.ticker("aapl")
 |      More specifically
 |      >>> df = df.ta.ticker("aapl", period="max", interval="1d", kind=None)
 |
 |      Changing the period of Historical Data
 |      Period is used instead of start/end
 |      >>> df = df.ta.ticker("aapl", period="1y")
 |
 |      Changing the period and interval of Historical Data
 |      Retrieves the past year in weeks
 |      >>> df = df.ta.ticker("aapl", period="1y", interval="1wk")
 |      Retrieves the past month in hours
 |      >>> df = df.ta.ticker("aapl", period="1mo", interval="1h")
 |
 |      Show everything
 |      >>> df = df.ta.ticker("aapl", kind="all")
 |
 |      Args:
 |          ticker (str): Any string for a ticker you would use with yfinance.
 |              Default: "SPY"
 |      Kwargs:
 |          kind (str): Options see above. Default: "history"
 |          ds (str): Data Source to use. Default: "yahoo"
 |          strategy (str | ta.Strategy): Which strategy to apply after
 |              downloading chart history. Default: None
 |
 |          See help(ta.yf) for additional kwargs
 |
 |      Returns:
 |          Exits if the DataFrame is empty or None
 |          Otherwise it returns a DataFrame
 |
 |  tos_stdevall(self, length=None, stds=None, offset=None, **kwargs)
 |
 |  trima(self, length=None, offset=None, **kwargs)
 |
 |  trix(self, length=None, signal=None, scalar=None, drift=None, offset=None, **kwargs)
 |
 |  true_range(self, drift=None, offset=None, **kwargs)
 |
 |  tsi(self, fast=None, slow=None, drift=None, mamode=None, offset=None, **kwargs)
 |
 |  tsignals(self, trend=None, asbool=None, trend_reset=None, trend_offset=None, offset=None, **kwargs)
 |
 |  ttm_trend(self, length=None, offset=None, **kwargs)
 |
 |  ui(self, length=None, scalar=None, offset=None, **kwargs)
 |
 |  uo(self, fast=None, medium=None, slow=None, fast_w=None, medium_w=None, slow_w=None, drift=None, offset=None, **kwargs)
 |
 |  variance(self, length=None, offset=None, **kwargs)
 |
 |  vhf(self, length=None, drift=None, offset=None, **kwargs)
 |
 |  vidya(self, length=None, offset=None, **kwargs)
 |
 |  vortex(self, drift=None, offset=None, **kwargs)
 |
 |  vp(self, width=None, percent=None, **kwargs)
 |
 |  vwap(self, anchor=None, offset=None, **kwargs)
 |
 |  vwma(self, volume=None, length=None, offset=None, **kwargs)
 |
 |  wcp(self, offset=None, **kwargs)
 |
 |  willr(self, length=None, percentage=True, offset=None, **kwargs)
 |
 |  wma(self, length=None, offset=None, **kwargs)
 |
 |  xsignals(self, signal=None, xa=None, xb=None, above=None, long=None, asbool=None, trend_reset=None, trend_offset=None, offset=None, **kwargs)
 |
 |  zlma(self, length=None, mamode=None, offset=None, **kwargs)
 |
 |  zscore(self, length=None, std=None, offset=None, **kwargs)
 |
 |  ----------------------------------------------------------------------
 |  Readonly properties defined here:
 |
 |  categories
 |      Returns the categories.
 |
 |  datetime_ordered
 |      Returns True if the index is a datetime and ordered.
 |
 |  last_run
 |      Returns the time when the DataFrame was last run.
 |
 |  reverse
 |      Reverses the DataFrame. Simply: df.iloc[::-1]
 |
 |  to_utc
 |      Sets the DataFrame index to UTC format
 |
 |  version
 |      Returns the version.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  adjusted
 |      property: df.ta.adjusted
 |
 |  cores
 |      Returns the categories.
 |
 |  exchange
 |      Returns the current Exchange. Default: "NYSE".
 |
 |  time_range
 |      Returns the time ranges of the DataFrame as a float. Default is in "years". help(ta.toal_time)
 |
 |  ----------------------------------------------------------------------

In [11]:
help(df.ta.indicators())

Pandas TA - Technical Analysis Indicators - v0.3.14b0
Total Indicators & Utilities: 205
Abbreviations:
    aberration, above, above_value, accbands, ad, adosc, adx, alma, amat, ao, aobv, apo, aroon, atr, bbands, below, below_value, bias, bop, brar, cci, cdl_pattern, cdl_z, cfo, cg, chop, cksp, cmf, cmo, coppock, cross, cross_value, cti, decay, decreasing, dema, dm, donchian, dpo, ebsw, efi, ema, entropy, eom, er, eri, fisher, fwma, ha, hilo, hl2, hlc3, hma, hwc, hwma, ichimoku, increasing, inertia, jma, kama, kc, kdj, kst, kurtosis, kvo, linreg, log_return, long_run, macd, mad, massi, mcgd, median, mfi, midpoint, midprice, mom, natr, nvi, obv, ohlc4, pdist, percent_return, pgo, ppo, psar, psl, pvi, pvo, pvol, pvr, pvt, pwma, qqe, qstick, quantile, rma, roc, rsi, rsx, rvgi, rvi, short_run, sinwma, skew, slope, sma, smi, squeeze, squeeze_pro, ssf, stc, stdev, stoch, stochrsi, supertrend, swma, t3, td_seq, tema, thermo, tos_stdevall, trima, trix, true_range, tsi, tsignals, ttm_trend, ui, uo, variance, vhf, vidya, vortex, vp, vwap, vwma, wcp, willr, wma, xsignals, zlma, zscore

Candle Patterns:
    2crows, 3blackcrows, 3inside, 3linestrike, 3outside, 3starsinsouth, 3whitesoldiers, abandonedbaby, advanceblock, belthold, breakaway, closingmarubozu, concealbabyswall, counterattack, darkcloudcover, doji, dojistar, dragonflydoji, engulfing, eveningdojistar, eveningstar, gapsidesidewhite, gravestonedoji, hammer, hangingman, harami, haramicross, highwave, hikkake, hikkakemod, homingpigeon, identical3crows, inneck, inside, invertedhammer, kicking, kickingbylength, ladderbottom, longleggeddoji, longline, marubozu, matchinglow, mathold, morningdojistar, morningstar, onneck, piercing, rickshawman, risefall3methods, separatinglines, shootingstar, shortline, spinningtop, stalledpattern, sticksandwich, takuri, tasukigap, thrusting, tristar, unique3river, upsidegap2crows, xsidegap3methods
Help on NoneType object:

class NoneType(object)
 |  Methods defined here:
 |
 |  __bool__(self, /)
 |      self != 0
 |
 |  __repr__(self, /)
 |      Return repr(self).
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.

In [18]:
help(ta.cci)

Help on function cci in module pandas_ta.momentum.cci:

cci(high, low, close, length=None, c=None, talib=None, offset=None, **kwargs)
    Commodity Channel Index (CCI)

    Commodity Channel Index is a momentum oscillator used to primarily identify
    overbought and oversold levels relative to a mean.

    Sources:
        https://www.tradingview.com/wiki/Commodity_Channel_Index_(CCI)

    Calculation:
        Default Inputs:
            length=14, c=0.015
        SMA = Simple Moving Average
        MAD = Mean Absolute Deviation
        tp = typical_price = hlc3 = (high + low + close) / 3
        mean_tp = SMA(tp, length)
        mad_tp = MAD(tp, length)
        CCI = (tp - mean_tp) / (c * mad_tp)

    Args:
        high (pd.Series): Series of 'high's
        low (pd.Series): Series of 'low's
        close (pd.Series): Series of 'close's
        length (int): It's period. Default: 14
        c (float): Scaling Constant. Default: 0.015
        talib (bool): If TA Lib is installed and talib is True, Returns the TA Lib
            version. Default: True
        offset (int): How many periods to offset the result. Default: 0

    Kwargs:
        fillna (value, optional): pd.DataFrame.fillna(value)
        fill_method (value, optional): Type of fill method

    Returns:
        pd.Series: New feature generated.

# Three Layers of Abstraction

## 1. Directly calling function

In [14]:
help(ta.rsi)

Help on function rsi in module pandas_ta.momentum.rsi:

rsi(close, length=None, scalar=None, talib=None, drift=None, offset=None, **kwargs)
    Relative Strength Index (RSI)

    The Relative Strength Index is popular momentum oscillator used to measure the
    velocity as well as the magnitude of directional price movements.

    Sources:
        https://www.tradingview.com/wiki/Relative_Strength_Index_(RSI)

    Calculation:
        Default Inputs:
            length=14, scalar=100, drift=1
        ABS = Absolute Value
        RMA = Rolling Moving Average

        diff = close.diff(drift)
        positive = diff if diff > 0 else 0
        negative = diff if diff < 0 else 0

        pos_avg = RMA(positive, length)
        neg_avg = ABS(RMA(negative, length))

        RSI = scalar * pos_avg / (pos_avg + neg_avg)

    Args:
        close (pd.Series): Series of 'close's
        length (int): It's period. Default: 14
        scalar (float): How much to magnify. Default: 100
        talib (bool): If TA Lib is installed and talib is True, Returns the TA Lib
            version. Default: True
        drift (int): The difference period. Default: 1
        offset (int): How many periods to offset the result. Default: 0

    Kwargs:
        fillna (value, optional): pd.DataFrame.fillna(value)
        fill_method (value, optional): Type of fill method

    Returns:
        pd.Series: New feature generated.

In [20]:
rsi = ta.rsi(close = df["Volume"], length = 40)
rsi

2022-09-08 09:30:00-04:00          NaN
2022-09-08 10:30:00-04:00          NaN
2022-09-08 11:30:00-04:00          NaN
2022-09-08 12:30:00-04:00          NaN
2022-09-08 13:30:00-04:00          NaN
                               ...
2022-10-07 12:30:00-04:00    48.768181
2022-10-07 13:30:00-04:00    48.405843
2022-10-07 14:30:00-04:00    49.013101
2022-10-07 15:30:00-04:00    50.227033
2022-10-07 16:00:00-04:00    47.023899
Name: RSI_40, Length: 155, dtype: float64

In [21]:
df["rsi"] = ta.rsi(close = df["Close"], length = 40)
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits,rsi
2022-09-08 09:30:00-04:00,154.639999,155.839996,154.369995,154.919998,20423405,0,0,NaN
2022-09-08 10:30:00-04:00,154.910004,156.360001,154.700195,155.990005,9445752,0,0,NaN
2022-09-08 11:30:00-04:00,155.985001,156.190002,152.679993,153.149902,12280244,0,0,NaN
2022-09-08 12:30:00-04:00,153.149994,154.020004,152.695007,153.733505,10943346,0,0,NaN
2022-09-08 13:30:00-04:00,153.740005,154.139999,153.229996,153.789993,7342717,0,0,NaN
...,...,...,...,...,...,...,...,...
2022-10-07 12:30:00-04:00,140.669998,140.720001,139.940002,140.279999,7685803,0,0,41.152446
2022-10-07 13:30:00-04:00,140.145004,140.600006,140.035004,140.077896,6175166,0,0,40.910621
2022-10-07 14:30:00-04:00,140.070007,140.535004,139.600006,139.721893,8536199,0,0,40.480855
2022-10-07 15:30:00-04:00,139.720001,140.490005,139.445007,140.080002,13306374,0,0,41.119013
2022-10-07 16:00:00-04:00,140.089996,140.089996,140.089996,140.089996,0,0,0,41.137078

## 2. Using dataframe accessor

In [22]:
help(ta.bbands)

Help on function bbands in module pandas_ta.volatility.bbands:

bbands(close, length=None, std=None, ddof=0, mamode=None, talib=None, offset=None, **kwargs)
    Bollinger Bands (BBANDS)

    A popular volatility indicator by John Bollinger.

    Sources:
        https://www.tradingview.com/wiki/Bollinger_Bands_(BB)

    Calculation:
        Default Inputs:
            length=5, std=2, mamode="sma", ddof=0
        EMA = Exponential Moving Average
        SMA = Simple Moving Average
        STDEV = Standard Deviation
        stdev = STDEV(close, length, ddof)
        if "ema":
            MID = EMA(close, length)
        else:
            MID = SMA(close, length)

        LOWER = MID - std * stdev
        UPPER = MID + std * stdev

        BANDWIDTH = 100 * (UPPER - LOWER) / MID
        PERCENT = (close - LOWER) / (UPPER - LOWER)

    Args:
        close (pd.Series): Series of 'close's
        length (int): The short period. Default: 5
        std (int): The long period. Default: 2
        ddof (int): Degrees of Freedom to use. Default: 0
        mamode (str): See ```help(ta.ma)```. Default: 'sma'
        talib (bool): If TA Lib is installed and talib is True, Returns the TA Lib
            version. Default: True
        offset (int): How many periods to offset the result. Default: 0

    Kwargs:
        fillna (value, optional): pd.DataFrame.fillna(value)
        fill_method (value, optional): Type of fill method

    Returns:
        pd.DataFrame: lower, mid, upper, bandwidth, and percent columns.

In [23]:
df.ta.bbands()

,BBL_5_2.0,BBM_5_2.0,BBU_5_2.0,BBB_5_2.0,BBP_5_2.0
2022-09-08 09:30:00-04:00,NaN,NaN,NaN,NaN,NaN
2022-09-08 10:30:00-04:00,NaN,NaN,NaN,NaN,NaN
2022-09-08 11:30:00-04:00,NaN,NaN,NaN,NaN,NaN
2022-09-08 12:30:00-04:00,NaN,NaN,NaN,NaN,NaN
2022-09-08 13:30:00-04:00,152.288308,154.316681,156.345054,2.628845,0.370170
...,...,...,...,...,...
2022-10-07 12:30:00-04:00,137.967317,141.759000,145.550682,5.349477,0.304968
2022-10-07 13:30:00-04:00,139.773876,140.676578,141.579279,1.283371,0.168394
2022-10-07 14:30:00-04:00,139.360636,140.396957,141.433279,1.476274,0.174298
2022-10-07 15:30:00-04:00,139.544406,140.166959,140.789511,0.888301,0.430161
2022-10-07 16:00:00-04:00,139.687928,140.049957,140.411986,0.517000,0.555298

In [26]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits,rsi,BBL_5_2.0,BBM_5_2.0,BBU_5_2.0,BBB_5_2.0,BBP_5_2.0
2022-09-08 09:30:00-04:00,154.639999,155.839996,154.369995,154.919998,20423405,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2022-09-08 10:30:00-04:00,154.910004,156.360001,154.700195,155.990005,9445752,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2022-09-08 11:30:00-04:00,155.985001,156.190002,152.679993,153.149902,12280244,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2022-09-08 12:30:00-04:00,153.149994,154.020004,152.695007,153.733505,10943346,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2022-09-08 13:30:00-04:00,153.740005,154.139999,153.229996,153.789993,7342717,0,0,NaN,152.288308,154.316681,156.345054,2.628845,0.370170
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-10-07 12:30:00-04:00,140.669998,140.720001,139.940002,140.279999,7685803,0,0,41.152446,137.967317,141.759000,145.550682,5.349477,0.304968
2022-10-07 13:30:00-04:00,140.145004,140.600006,140.035004,140.077896,6175166,0,0,40.910621,139.773876,140.676578,141.579279,1.283371,0.168394
2022-10-07 14:30:00-04:00,140.070007,140.535004,139.600006,139.721893,8536199,0,0,40.480855,139.360636,140.396957,141.433279,1.476274,0.174298
2022-10-07 15:30:00-04:00,139.720001,140.490005,139.445007,140.080002,13306374,0,0,41.119013,139.544406,140.166959,140.789511,0.888301,0.430161
2022-10-07 16:00:00-04:00,140.089996,140.089996,140.089996,140.089996,0,0,0,41.137078,139.687928,140.049957,140.411986,0.517000,0.555298

In [25]:
df.ta.bbands(append=True)

,BBL_5_2.0,BBM_5_2.0,BBU_5_2.0,BBB_5_2.0,BBP_5_2.0
2022-09-08 09:30:00-04:00,NaN,NaN,NaN,NaN,NaN
2022-09-08 10:30:00-04:00,NaN,NaN,NaN,NaN,NaN
2022-09-08 11:30:00-04:00,NaN,NaN,NaN,NaN,NaN
2022-09-08 12:30:00-04:00,NaN,NaN,NaN,NaN,NaN
2022-09-08 13:30:00-04:00,152.288308,154.316681,156.345054,2.628845,0.370170
...,...,...,...,...,...
2022-10-07 12:30:00-04:00,137.967317,141.759000,145.550682,5.349477,0.304968
2022-10-07 13:30:00-04:00,139.773876,140.676578,141.579279,1.283371,0.168394
2022-10-07 14:30:00-04:00,139.360636,140.396957,141.433279,1.476274,0.174298
2022-10-07 15:30:00-04:00,139.544406,140.166959,140.789511,0.888301,0.430161
2022-10-07 16:00:00-04:00,139.687928,140.049957,140.411986,0.517000,0.555298

In [24]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits,rsi,RSI_14,BBL_5_2.0,BBM_5_2.0,BBU_5_2.0,BBB_5_2.0,BBP_5_2.0
2022-09-08 09:30:00-04:00,154.639999,155.839996,154.369995,154.919998,20423405,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-09-08 10:30:00-04:00,154.910004,156.360001,154.700195,155.990005,9445752,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-09-08 11:30:00-04:00,155.985001,156.190002,152.679993,153.149902,12280244,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-09-08 12:30:00-04:00,153.149994,154.020004,152.695007,153.733505,10943346,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-09-08 13:30:00-04:00,153.740005,154.139999,153.229996,153.789993,7342717,0,0,NaN,NaN,152.288308,154.316681,156.345054,2.628845,0.370170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-10-07 12:30:00-04:00,140.669998,140.720001,139.940002,140.279999,7685803,0,0,40.853757,32.022693,137.967317,141.759000,145.550682,5.349477,0.304968
2022-10-07 13:30:00-04:00,140.145004,140.600006,140.035004,140.077896,6175166,0,0,40.607664,31.428617,139.773876,140.676578,141.579279,1.283371,0.168394
2022-10-07 14:30:00-04:00,140.070007,140.535004,139.600006,139.721893,8536199,0,0,40.170491,30.360166,139.360636,140.396957,141.433279,1.476274,0.174298
2022-10-07 15:30:00-04:00,139.720001,140.490005,139.445007,140.080002,13306374,0,0,40.827724,32.833747,139.544406,140.166959,140.789511,0.888301,0.430161
2022-10-07 16:00:00-04:00,140.089996,140.089996,140.089996,140.089996,0,0,0,40.846325,32.905376,139.687928,140.049957,140.411986,0.517000,0.555298

## Column name formatting

Pandas-ta has some flexibility with column names, see this dictionary from `core.py`

```
common_names = {
    "Date": "date",
    "Time": "time",
    "Timestamp": "timestamp",
    "Datetime": "datetime",
    "Open": "open",
    "High": "high",
    "Low": "low",
    "Close": "close",
    "Adj Close": "adj_close",
    "Volume": "volume",
    "Dividends": "dividends",
    "Stock Splits": "split",
}
```

### Chaining Indicators

In [29]:
# ohlc4 = (open + high + low + close)/4
df.ta.ema(close=df.ta.ohlc4(), length=10, suffix="OHLC4", prefix="test", append = True)

2022-09-08 09:30:00-04:00           NaN
2022-09-08 10:30:00-04:00           NaN
2022-09-08 11:30:00-04:00           NaN
2022-09-08 12:30:00-04:00           NaN
2022-09-08 13:30:00-04:00           NaN
                                ...
2022-10-07 12:30:00-04:00    143.181928
2022-10-07 13:30:00-04:00    142.642391
2022-10-07 14:30:00-04:00    142.158634
2022-10-07 15:30:00-04:00    141.754111
2022-10-07 16:00:00-04:00    141.451544
Name: test_EMA_10_OHLC4, Length: 155, dtype: float64

In [28]:
df.ta.ohlc4()

2022-09-08 09:30:00-04:00    154.942497
2022-09-08 10:30:00-04:00    155.490051
2022-09-08 11:30:00-04:00    154.501225
2022-09-08 12:30:00-04:00    153.399628
2022-09-08 13:30:00-04:00    153.724998
                                ...
2022-10-07 12:30:00-04:00    140.402500
2022-10-07 13:30:00-04:00    140.214478
2022-10-07 14:30:00-04:00    139.981728
2022-10-07 15:30:00-04:00    139.933754
2022-10-07 16:00:00-04:00    140.089996
Name: OHLC4, Length: 155, dtype: float64

## 3. Strategies

In [27]:
df = df.ta.ticker("aapl")

In [28]:
MyStrategy = ta.Strategy(
    name="DCSMA10",
    ta=[
        {"kind": "ohlc4"},
        {"kind": "sma", "length": 10},
        {"kind": "donchian", "lower_length": 10, "upper_length": 15},
        {"kind": "ema", "close": "SMA_10", "length": 10, "suffix": "OHLC4"},
    ]
)

# (2) Run the Strategy
df.ta.strategy(MyStrategy)

In [29]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits,OHLC4,SMA_10,DCL_10_15,DCM_10_15,DCU_10_15,EMA_10_OHLC4
Date,,,,,,,,,,,,,
1980-12-12 00:00:00-05:00,0.100039,0.100474,0.100039,0.100039,469033600,0.0,0.0,0.100148,NaN,NaN,NaN,NaN,NaN
1980-12-15 00:00:00-05:00,0.095255,0.095255,0.094820,0.094820,175884800,0.0,0.0,0.095038,NaN,NaN,NaN,NaN,NaN
1980-12-16 00:00:00-05:00,0.088296,0.088296,0.087861,0.087861,105728000,0.0,0.0,0.088078,NaN,NaN,NaN,NaN,NaN
1980-12-17 00:00:00-05:00,0.090035,0.090470,0.090035,0.090035,86441600,0.0,0.0,0.090144,NaN,NaN,NaN,NaN,NaN
1980-12-18 00:00:00-05:00,0.092646,0.093081,0.092646,0.092646,73449600,0.0,0.0,0.092754,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-10-03 00:00:00-04:00,138.210007,143.070007,137.690002,142.449997,114311700,0.0,0.0,140.355003,148.928998,137.690002,149.114998,160.539993,152.575156
2022-10-04 00:00:00-04:00,145.029999,146.220001,144.259995,146.100006,87830100,0.0,0.0,145.402500,147.848999,137.690002,148.215004,158.740005,151.715855
2022-10-05 00:00:00-04:00,144.070007,147.380005,143.009995,146.399994,79471000,0.0,0.0,145.215000,147.116998,137.690002,148.215004,158.740005,150.879699
2022-10-06 00:00:00-04:00,145.809998,147.539993,145.220001,145.429993,68402200,0.0,0.0,145.999996,146.385997,137.690002,148.215004,158.740005,150.062662
2022-10-07 00:00:00-04:00,142.539993,143.100006,139.449997,140.089996,85859100,0.0,0.0,141.294998,145.351997,137.690002,148.215004,158.740005,149.206178

## All the indicators

In [32]:
df = df.ta.ticker("aapl")
df.ta.cores = 0
df.ta.strategy("All", timed = True)
df

/tmp/ipykernel_19648/2946661692.py:3: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.ta.strategy("All", timed = True)

[i] Runtime: 13913.2577 ms (13.9133 s)

/tmp/ipykernel_19648/2946661692.py:3: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df.ta.strategy("All", timed = True)
/tmp/ipykernel_19648/2946661692.py:3: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df.ta.strategy("All", timed = True)

,Open,High,Low,Close,Volume,Dividends,Stock Splits,ABER_ZG_5_15,ABER_SG_5_15,ABER_XG_5_15,...,VIDYA_14,VTXP_14,VTXM_14,VWAP_D,VWMA_10,WCP,WILLR_14,WMA_10,ZL_EMA_10,ZS_30
Date,,,,,,,,,,,,,,,,,,,,,
1980-12-12 00:00:00-05:00,0.100039,0.100474,0.100039,0.100039,469033600,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,0.100184,NaN,0.100148,NaN,NaN,NaN,NaN
1980-12-15 00:00:00-05:00,0.095255,0.095255,0.094820,0.094820,175884800,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,0.094965,NaN,0.094929,NaN,NaN,NaN,NaN
1980-12-16 00:00:00-05:00,0.088296,0.088296,0.087861,0.087861,105728000,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,0.088006,NaN,0.087969,NaN,NaN,NaN,NaN
1980-12-17 00:00:00-05:00,0.090035,0.090470,0.090035,0.090035,86441600,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,0.090180,NaN,0.090144,NaN,NaN,NaN,NaN
1980-12-18 00:00:00-05:00,0.092646,0.093081,0.092646,0.092646,73449600,0.0,0.0,0.093225,NaN,NaN,...,NaN,NaN,NaN,0.092791,NaN,0.092754,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-10-03 00:00:00-04:00,138.210007,143.070007,137.690002,142.449997,114311700,0.0,0.0,144.942666,149.814706,140.070625,...,155.686293,0.683566,1.154799,141.070002,148.430145,141.415001,-77.387203,146.285634,141.553455,-1.798987
2022-10-04 00:00:00-04:00,145.029999,146.220001,144.259995,146.100006,87830100,0.0,0.0,143.619333,148.417904,138.820762,...,155.392509,0.748936,1.068794,145.526667,147.380298,145.670002,-60.047494,145.771272,141.700103,-1.229065
2022-10-05 00:00:00-04:00,144.070007,147.380005,143.009995,146.399994,79471000,0.0,0.0,143.050666,147.820667,138.280666,...,155.201270,0.765295,1.026783,145.596664,146.686473,145.797497,-58.622374,145.507816,143.267355,-1.125067
2022-10-06 00:00:00-04:00,145.809998,147.539993,145.220001,145.429993,68402200,0.0,0.0,143.604666,148.211333,138.998000,...,155.014340,0.848831,0.983685,146.063329,146.089857,145.904995,-63.230456,145.201088,144.975107,-1.207937
2022-10-07 00:00:00-04:00,142.539993,143.100006,139.449997,140.089996,85859100,0.0,0.0,143.827333,148.525554,139.129111,...,154.266499,0.784179,1.060046,140.880000,145.170454,140.682499,-88.598605,144.056360,143.657814,-1.951891

In [31]:
df.columns

Index(['Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits',
       'ABER_ZG_5_15', 'ABER_SG_5_15', 'ABER_XG_5_15',
       ...
       'VIDYA_14', 'VTXP_14', 'VTXM_14', 'VWAP_D', 'VWMA_10', 'WCP',
       'WILLR_14', 'WMA_10', 'ZL_EMA_10', 'ZS_30'],
      dtype='object', length=285)

## Custom Column names
(No multi-processing)

In [5]:
df = df.ta.ticker("aapl")
df.ta.strategy("candles")
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits,CDL_2CROWS,CDL_3BLACKCROWS,CDL_3INSIDE,...,CDL_UPSIDEGAP2CROWS,CDL_XSIDEGAP3METHODS,open_Z_30_1,high_Z_30_1,low_Z_30_1,close_Z_30_1,HA_open,HA_high,HA_low,HA_close
Date,,,,,,,,,,,,,,,,,,,,,
1980-12-12 00:00:00-05:00,0.100039,0.100474,0.100039,0.100039,469033600,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,0.100039,0.100474,0.100039,0.100148
1980-12-15 00:00:00-05:00,0.095255,0.095255,0.094820,0.094820,175884800,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,0.100094,0.100094,0.094820,0.095038
1980-12-16 00:00:00-05:00,0.088296,0.088296,0.087861,0.087861,105728000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,0.097566,0.097566,0.087861,0.088078
1980-12-17 00:00:00-05:00,0.090035,0.090470,0.090035,0.090035,86441600,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,0.092822,0.092822,0.090035,0.090144
1980-12-18 00:00:00-05:00,0.092646,0.093081,0.092646,0.092646,73449600,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,0.091483,0.093081,0.091483,0.092754
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-10-03 00:00:00-04:00,138.210007,143.070007,137.690002,142.449997,114311700,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-2.308389,-2.064321,-2.081569,-1.798987,143.589255,143.589255,137.690002,140.355003
2022-10-04 00:00:00-04:00,145.029999,146.220001,144.259995,146.100006,87830100,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-1.354988,-1.529249,-1.167332,-1.229065,141.972129,146.220001,141.972129,145.402500
2022-10-05 00:00:00-04:00,144.070007,147.380005,143.009995,146.399994,79471000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-1.392314,-1.290141,-1.269122,-1.125067,143.687315,147.380005,143.009995,145.215000
2022-10-06 00:00:00-04:00,145.809998,147.539993,145.220001,145.429993,68402200,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-1.099441,-1.198773,-0.916395,-1.207937,144.451157,147.539993,144.451157,145.999996
2022-10-07 00:00:00-04:00,142.539993,143.100006,139.449997,140.089996,85859100,0.0,0.0,0.0,0.0,-100.0,...,0.0,0.0,-1.483835,-1.759172,-1.719395,-1.951891,145.225577,145.225577,139.449997,141.294998

In [35]:
df = df.ta.ticker("aapl")
MyStrategy = ta.Strategy(
    name="DCSMA10",
    ta=[
        {"kind": "ohlc4"},
        {"kind": "sma", "length": 10, "col_names":("SMA",)},
        {"kind": "donchian", "lower_length": 10, "upper_length": 15, "col_names":("DLC","DCM","DCU")},
        {"kind": "ema", "close": "OHLC4", "length": 10, "suffix": "OHLC4", "col_names":("EMA2",)},
    ]
)

# (2) Run the Strategy
df.ta.strategy(MyStrategy, length= 20)
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits,OHLC4,SMA,DLC,DCM,DCU,EMA2
Date,,,,,,,,,,,,,
1980-12-12 00:00:00-05:00,0.100039,0.100474,0.100039,0.100039,469033600,0.0,0.0,0.100148,NaN,NaN,NaN,NaN,NaN
1980-12-15 00:00:00-05:00,0.095255,0.095255,0.094820,0.094820,175884800,0.0,0.0,0.095038,NaN,NaN,NaN,NaN,NaN
1980-12-16 00:00:00-05:00,0.088296,0.088296,0.087861,0.087861,105728000,0.0,0.0,0.088078,NaN,NaN,NaN,NaN,NaN
1980-12-17 00:00:00-05:00,0.090035,0.090470,0.090035,0.090035,86441600,0.0,0.0,0.090144,NaN,NaN,NaN,NaN,NaN
1980-12-18 00:00:00-05:00,0.092646,0.093081,0.092646,0.092646,73449600,0.0,0.0,0.092754,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-10-03 00:00:00-04:00,138.210007,143.070007,137.690002,142.449997,114311700,0.0,0.0,140.355003,152.086998,137.690002,149.114998,160.539993,151.337411
2022-10-04 00:00:00-04:00,145.029999,146.220001,144.259995,146.100006,87830100,0.0,0.0,145.402500,151.665498,137.690002,148.215004,158.740005,150.772181
2022-10-05 00:00:00-04:00,144.070007,147.380005,143.009995,146.399994,79471000,0.0,0.0,145.215000,151.187498,137.690002,148.215004,158.740005,150.242926
2022-10-06 00:00:00-04:00,145.809998,147.539993,145.220001,145.429993,68402200,0.0,0.0,145.999996,150.735997,137.690002,148.215004,158.740005,149.838837
2022-10-07 00:00:00-04:00,142.539993,143.100006,139.449997,140.089996,85859100,0.0,0.0,141.294998,149.871997,137.690002,148.215004,158.740005,149.025138

In [37]:
df = df.ta.ticker("aapl")
df.ta.strategy("candles")
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits,CDL_2CROWS,CDL_3BLACKCROWS,CDL_3INSIDE,...,CDL_UPSIDEGAP2CROWS,CDL_XSIDEGAP3METHODS,open_Z_30_1,high_Z_30_1,low_Z_30_1,close_Z_30_1,HA_open,HA_high,HA_low,HA_close
Date,,,,,,,,,,,,,,,,,,,,,
1980-12-12 00:00:00-05:00,0.100039,0.100474,0.100039,0.100039,469033600,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,0.100039,0.100474,0.100039,0.100148
1980-12-15 00:00:00-05:00,0.095255,0.095255,0.094820,0.094820,175884800,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,0.100094,0.100094,0.094820,0.095038
1980-12-16 00:00:00-05:00,0.088296,0.088296,0.087861,0.087861,105728000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,0.097566,0.097566,0.087861,0.088078
1980-12-17 00:00:00-05:00,0.090035,0.090470,0.090035,0.090035,86441600,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,0.092822,0.092822,0.090035,0.090144
1980-12-18 00:00:00-05:00,0.092646,0.093081,0.092646,0.092646,73449600,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,0.091483,0.093081,0.091483,0.092754
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-10-03 00:00:00-04:00,138.210007,143.070007,137.690002,142.449997,114311700,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-2.308389,-2.064321,-2.081569,-1.798987,143.589255,143.589255,137.690002,140.355003
2022-10-04 00:00:00-04:00,145.029999,146.220001,144.259995,146.100006,87830100,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-1.354988,-1.529249,-1.167332,-1.229065,141.972129,146.220001,141.972129,145.402500
2022-10-05 00:00:00-04:00,144.070007,147.380005,143.009995,146.399994,79471000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-1.392314,-1.290141,-1.269122,-1.125067,143.687315,147.380005,143.009995,145.215000
2022-10-06 00:00:00-04:00,145.809998,147.539993,145.220001,145.429993,68402200,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-1.099441,-1.198773,-0.916395,-1.207937,144.451157,147.539993,144.451157,145.999996
2022-10-07 00:00:00-04:00,142.539993,143.100006,139.449997,140.089996,85859100,0.0,0.0,0.0,0.0,-100.0,...,0.0,0.0,-1.483835,-1.759172,-1.719395,-1.951891,145.225577,145.225577,139.449997,141.294998

In [7]:
df.ta.categories

['candles',
 'cycles',
 'momentum',
 'overlap',
 'performance',
 'statistics',
 'trend',
 'volatility',
 'volume']